# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently. 
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Amanuel Tesfaye
email: attesfaye24@amherst.edu
description: >- # this means to ignore newlines until "baseurl:"
  Here, you'll find a curated collection of my creative work and accomplishments. 
  Explore my projects, photography work, and get a glimpse of my professional 
  journey! I invite you to discover my passion for problem solving and photography
  and my attempt to bridge the gap between the two worlds.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: amanuelttesfaye
github_username: Amana28

# Build settings
plugins:
  - jekyll-feed
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".

sass:
  sass_dir: _sass

# Documentation: jekyllrb.com/docs/collections
collections_dir: _collections
collections:
  blog:
    title: Blog
    output: true
    permalink: /blog/:title
    canonical_link: https://www.your-site-title.com/blog/:title
  projects:
    title: Projects
    output: true
    permalink: /projects/:title
    canonical_link: https://www.your-site-title.com/projects/:title

# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .DS_Store
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
